### ISSUE TITLE
missing GAT_dgl file, graph_feature_transfomr and unable to run FE-STGNN 

### ISSUE THREAD

**Issue by PasqualeDellaRosa** [haijunkenan/FE-STGNN#1]
Hello,

First of all, I was pleased to read your FE-STGNN: Spatio-Temporal Graph Neural Network with Functional and Effective Connectivity Fusion for MCI Diagnosis paper and really appreciated your model and the framework, combining FC and EC. 

I’m writing you as we are willing to use the FE-STGNN network for classification purposes in clinical groups on a rsfMRI pediatric dataset, however we are having serious problems in implementing the FE-STGNN package on our machine, with errors due to the impossibility to find or import as following.

•	We installed/compiled all the necessary pakages as reported in the readme
•	We are unable to find in your repo, nor in any other repository the GAT_dgl.py recalled In the model.py at
o	Line 20: from GAT_dgl import GATModel
o	Line 21: from GAT_dgl import Replace_GAT
•	We are unable to find in your repo, nor in any other github repository, the library graph_feature_transfom recalled In the model.py at
o	Line22: from graph_feature_transfomr import GraphModel

Please see screenshots
![Screenshot 2024-05-17 alle 17 22 43](https://github.com/haijunkenan/FE-STGNN/assets/89928658/ea898775-0b1e-46ca-a8f7-cfe496d14e1c)
![Screenshot 2024-05-17 alle 17 22 53](https://github.com/haijunkenan/FE-STGNN/assets/89928658/a451a895-fd7c-4bdc-8552-3582a8e223e2)

Could you please verify if we are doing something wrong, give us hints, the necessary feedback or possibly provide us with the solution for implementing, setting-up FE-STGNN and run it on our data?

We would truly appreciate your support, awaiting any feedback you can give us.
Thank you very much
All the best
Pasquale Anthony Della Rosa

**Comment by DongDChen** [comment]
Dear Dr. Pasquale Anthony Della Rosa, and Dr. Tagliaferri Ilario:

Thank you for your question and sorry for the delayed reply.

The GAT\Replace_GAT\GraphModel modules were ablation modules that we conducted during the trial phase. Thus, the final version of our proposed method actually does not use these modules.

If you are only interested in using the proposed method as described in the paper, you can simply ignore and annotate these irrelevant codes.

If you are also interested in trying out these ablation modules, we have further provided the corresponding file (GAT_dgl.py, graph_feature_transfomr.py) upon request in the email attachment.


Best.,
Dongdong Chen
